/**:
  ros__parameters:
    camera:
      i_calibration_dump: true
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: RGBD
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
